# codemagic.yaml — iOS IPA (no codesign)
workflows:
  ios-ipa-release-no-sign:
    name: iOS IPA Release (No codesign)
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - ios/Pods
        - ~/.gradle/caches
    scripts:
      - name: Flutter pub get
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA (release, no codesign)
        # Tạo IPA không ký để bạn ký bằng Sideloadly sau
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.xcarchive
      - build/ios/ipa/*.dSYM.zip