workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Flutter clean & pub get
        script: |
          set -e
          flutter --version
          flutter clean
          flutter pub get
      - name: Clean CocoaPods
        script: |
          set -e
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS (release, no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign

      - name: Package IPA
        script: |
          # Chỉ fail khi lệnh lỗi & lỗi pipeline, KHÔNG fail vì biến unset
          set -eo pipefail

          APP_NAME="Runner"

          # Tìm Runner.app được build
          APP_DIR="$(/usr/bin/find "$CM_BUILD_DIR/build/ios/iphoneos" -maxdepth 1 -type d -name "${APP_NAME}.app" -print -quit)"
          if [[ -z "$APP_DIR" ]]; then
            echo "❌ ${APP_NAME}.app not found in build/ios/iphoneos"
            ls -la "$CM_BUILD_DIR/build/ios/iphoneos" || true
            exit 1
          fi

          # Chọn thư mục artifacts (tương thích cả 2 biến của Codemagic)
          ARTIFACTS_DIR="${CM_ARTIFACTS:-${CM_EXPORT_DIR:-$HOME/artifacts}}"
          mkdir -p "$ARTIFACTS_DIR"

          # Đóng gói IPA
          cd "$(dirname "$APP_DIR")"
          rm -rf Payload
          mkdir -p Payload
          cp -R "${APP_NAME}.app" Payload/

          /usr/bin/zip -qry "${APP_NAME}.zip" Payload
          mv "${APP_NAME}.zip" "${ARTIFACTS_DIR}/${APP_NAME}.ipa"

          echo "✅ IPA saved to: ${ARTIFACTS_DIR}/${APP_NAME}.ipa"

    artifacts:
      # Gom cả hai trường hợp đường dẫn artifacts
      - $CM_ARTIFACTS/*.ipa
      - $CM_EXPORT_DIR/*.ipa
      - $HOME/artifacts/*.ipa

    publishing:
      email:
        recipients:
          - duydo2823@gmail.com
        notify:
          success: true
          failure: true
