workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_NAME: "Runner"
    scripts:
      - name: Clean CocoaPods
        script: |
          set -e
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Flutter clean & get
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS (release, no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          cp -R Runner.app Payload/
          /usr/bin/zip -yr "${APP_NAME}.zip" Payload
          mv "${APP_NAME}.zip" "$CM_ARTIFACTS/${APP_NAME}.ipa"
    artifacts:
      - $CM_ARTIFACTS/*.ipa
    publishing:
      email:
        recipients:
          - duydo2823@email.com
        notify:
          success: true
          failure: true
