scripts:
  - name: Flutter clean & pub get
    script: |
      flutter clean
      flutter pub get
      flutter --version
      flutter precache --ios

  - name: CocoaPods (optional clean)
    script: |
      cd ios
      rm -rf Pods Podfile.lock
      pod repo update
      pod install --repo-update
      cd -

  - name: Build iOS (release, no codesign)
    script: |
      flutter build ios --release --no-codesign

  - name: Package IPA
    script: |
      cd build/ios/iphoneos
      rm -rf Payload
      mkdir Payload
      cp -R Runner.app Payload/
      /usr/bin/zip -yr "Runner.zip" Payload
      mv "Runner.zip" "$CM_BUILD_DIR/Runner.ipa"
