workflows:
  ios-release:
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Flutter clean & pub get
        script: |
          flutter clean
          flutter pub get
          flutter --version
          flutter precache --ios

      - name: Show Podfile (debug)
        script: |
          echo "===== ios/Podfile begin ====="
          sed -n '1,120p' ios/Podfile
          echo "===== ios/Podfile end ====="
          test -f ios/Flutter/Generated.xcconfig || (echo "Missing ios/Flutter/Generated.xcconfig"; exit 1)

      - name: Build iOS (release, no codesign)
        script: |
          flutter build ios --release --no-codesign

      - name: Package IPA
        script: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          cp -R Runner.app Payload/
          /usr/bin/zip -yr "Runner.zip" Payload
          mv "Runner.zip" "$CM_BUILD_DIR/Runner.ipa"

    artifacts:
      - $CM_BUILD_DIR/Runner.ipa
