workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      vars: { APP_NAME: "Runner" }
    scripts:
      - name: Flutter precache (iOS)
        script: |
          set -e
          flutter precache --ios
      - name: Flutter clean & get
        script: |
          set -e
          flutter clean
          flutter pub get
      - name: CocoaPods install
        script: |
          set -e
          rm -rf ios/Pods ios/Podfile.lock
          cd ios
          pod repo update
          pod install
          cd ..
      - name: Build iOS (release, no codesign)
        script: |
          set -e
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          set -euo pipefail
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          cp -R Runner.app Payload/
          /usr/bin/zip -yr "${APP_NAME}.zip" Payload
          ART_DIR="${CM_ARTIFACTS:-$CM_EXPORT_DIR}"
          mkdir -p "$ART_DIR"
          mv "${APP_NAME}.zip" "$ART_DIR/${APP_NAME}.ipa"
    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_ARTIFACTS/*.ipa
