# ios/Podfile
platform :ios, '13.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Thiết lập Flutter CocoaPods
flutter_ios_podfile_setup

target 'Runner' do
  # BẮT BUỘC cho plugin iOS hiện nay để tránh lỗi header Flutter.h
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Cài tất cả pods của Flutter/plugins
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Bắt buộc: thêm build settings của Flutter (search path, v.v.)
    flutter_additional_ios_build_settings(target)

    # Khớp iOS minimum
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
